---
- name: Install ferm and ipset
  apt:
    name:
      - ferm
      - ipset

- name: Copy ferm configuration files
  copy: "{{ ferm_deploy_config_files_defaults | combine( config ) }}"
  loop: "{{ ferm_deploy_configs }}"
  loop_control:
    loop_var: config
  notify: Enable and reload ferm

